DROP TABLE IF EXISTS hotel_reservation_system.city;

CREATE TABLE hotel_reservation_system.city (
    `CITY_ID` INT NOT NULL AUTO_INCREMENT,
    `CITY_NAME` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (`CITY_ID`)
);

DROP TABLE IF EXISTS hotel_reservation_system.lookup;

CREATE TABLE hotel_reservation_system.lookup (
    `LOOKUP_ID` INT NOT NULL AUTO_INCREMENT,
    `LOOKUP_NAME` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (`LOOKUP_ID`)
);

DROP TABLE IF EXISTS hotel_reservation_system.lookup_info;

CREATE TABLE hotel_reservation_system.lookup_info (
    `LOOKUP_INFO_ID` INT NOT NULL AUTO_INCREMENT,
    `LOOKUP_INFO_NAME` VARCHAR(50) DEFAULT NULL,
    `LOOKUP_ID` INT DEFAULT NULL,
    PRIMARY KEY (`LOOKUP_INFO_ID`),
    KEY `FK_LOOKUP_ID` (`LOOKUP_ID`),
    CONSTRAINT `FK_LOOKUP_ID` FOREIGN KEY (`LOOKUP_ID`)
        REFERENCES `lookup` (`LOOKUP_ID`)
);

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS hotel_reservation_system.hotel;

CREATE TABLE hotel_reservation_system.hotel (
    `HOTEL_ID` INT NOT NULL AUTO_INCREMENT,
    `HOTEL_NAME` VARCHAR(50) DEFAULT NULL,
    `NO_OF_ROOMS` INT DEFAULT NULL,
    `ROOM_TYPE_ID` INT DEFAULT NULL,
    `PRICE` INT DEFAULT NULL,
    `GST` FLOAT DEFAULT NULL,
    `TOTAL` FLOAT DEFAULT NULL,
    `CITY_ID` INT DEFAULT NULL,
    PRIMARY KEY (`HOTEL_ID`),
    KEY `FK_CITY_ID` (`CITY_ID`),
    KEY `FK_ROOM_TYPE` (`ROOM_TYPE_ID`),
    CONSTRAINT `FK_CITY_ID` FOREIGN KEY (`CITY_ID`)
        REFERENCES `city` (`CITY_ID`),
    CONSTRAINT `FK_ROOM_TYPE_ID` FOREIGN KEY (`ROOM_TYPE_ID`)
        REFERENCES `lookup_info` (`LOOKUP_INFO_ID`)
);

DROP TABLE IF EXISTS hotel_reservation_system.booking;

CREATE TABLE hotel_reservation_system.booking (
    `BOOKING_ID` INT NOT NULL AUTO_INCREMENT,
    `BOOKING_NO` VARCHAR(50) DEFAULT NULL,
    `GUEST_NAME` VARCHAR(50) DEFAULT NULL,
    `AGE` INT DEFAULT NULL,
    `EMAIL_ID` VARCHAR(50) DEFAULT NULL,
    `MOBILE_NO` VARCHAR(20) DEFAULT NULL,
    `ROOM_TYPE_ID` INT DEFAULT NULL,
    `HOTEL_ID` INT DEFAULT NULL,
    `CREATED_DATE` TIMESTAMP DEFAULT NULL,
    `ACTIVE_STATUS` INT DEFAULT NULL,
    PRIMARY KEY (`BOOKING_ID`),
    KEY FK_ROOM_TYPE (`ROOM_TYPE_ID`),
    KEY FK_HOTEL (`HOTEL_ID`),
    CONSTRAINT `ROOM_TYPE_ID` FOREIGN KEY (`ROOM_TYPE_ID`)
        REFERENCES `lookup_info` (`LOOKUP_INFO_ID`),
    CONSTRAINT `HOTEL_ID` FOREIGN KEY (`HOTEL_ID`)
        REFERENCES `hotel` (`HOTEL_ID`)
);

SET FOREIGN_KEY_CHECKS = 1;